import { BookOpen } from 'lucide-react';
import { CodeBlock } from './CodeBlock';
import './guides.css';

const sections = [['overview', 'How it works'], ['owner', 'Owner setup'], ['actions', 'Actions & MCP'], ['generator', 'Browser generator'], ['maintenance', 'Maintain SafeGen'], ['troubleshooting', 'Troubleshooting']] as const;
const repo = 'https://github.com/poorvith-mp/safegen/blob/main/';

export function DocumentationHub() {
  return <section className="guide-page" aria-labelledby="docs-title">
    <header className="guide-heading"><p className="guide-eyebrow"><BookOpen size={16} /> The SafeGen handbook</p><h1 id="docs-title">Understand it.<br />Set it up. Keep control.</h1><p>Start with the browser generator, or connect an agent to a local action broker. These are separate tools with separate responsibilities.</p></header>
    <div className="handbook-layout"><nav className="handbook-nav" aria-label="Documentation sections">{sections.map(([id, label]) => <a key={id} href={`/docs#${id}`}>{label}</a>)}<a href={`${repo}docs/architecture.md`}>Architecture on GitHub ↗</a></nav><div className="handbook-body">
      <article id="overview"><span className="guide-eyebrow">01 / The model</span><h2>Give an agent an action, not an API key.</h2><p>SafeGen’s purpose is to let an agent do useful work without putting provider credentials into its context. A local owner broker holds the encrypted vault, checks named actions and calls a pinned provider after your approval. The agent receives a request ID and a limited status result.</p><ol><li>The agent requests a named action against an owner-configured connection.</li><li>You inspect the target and parameters in the private owner browser.</li><li>The broker authenticates directly with GitHub, Cloudflare, or npm.</li><li>The agent receives only allowed result fields. These nonsecret results may reach its model provider.</li></ol><p>The website never connects to the broker. It generates credentials in your browser and hosts these guides.</p><a href="/setup">Open the agent setup guide →</a></article>
      <article id="owner"><span className="guide-eyebrow">02 / Human owner only</span><h2>Prepare a private owner environment.</h2><p>Before adding a real token, follow the <a href={`${repo}docs/isolation.md`}>OS isolation guide</a>. Use separate standard OS accounts and separate private code, dependencies, Node runtime and browser sessions. The agent must not read or modify the owner environment or automate its screen. Basic startup checks are not a full machine audit.</p><p>Build the current repository with Node 22.13+ in each account’s own installation. CLI 3 is a source release; older npm CLI versions use a different credential-returning model.</p><CodeBlock label="Build from source">{'git clone https://github.com/poorvith-mp/safegen.git\ncd safegen\nnpm ci\nnpm run build:packages'}</CodeBlock><p>In the private owner terminal, initialize the vault and add only the connections you need. Commands prompt for secrets locally. Use minimum provider permissions and token expiry.</p><CodeBlock label="Owner commands">{'node packages/cli/dist/index.js vault init\nnode packages/cli/dist/index.js broker connect --provider github --name work --repository example/project\nnode packages/cli/dist/index.js broker connect --provider cloudflare --name edge --account-id YOUR_ACCOUNT_ID --worker example-worker\nnode packages/cli/dist/index.js broker connect --provider npm --name pkg --package @poorvithmp/safegen-cli --tarball-dir ABSOLUTE_PATH_TO_TARBALL_DIR\nnode packages/cli/dist/index.js broker start --agent-user YOUR_AGENT_OS_USERNAME'}</CodeBlock><aside className="guide-callout"><strong>The private control link belongs only to you.</strong><p>Open the printed link in the isolated owner browser. Never paste it, a provider token or a master password into agent chat. Keep the owner account free of agent automation. Administrator/root access and a compromised owner environment are outside this protection.</p></aside></article>
      <article id="actions"><span className="guide-eyebrow">03 / Request and approve</span><h2>A small, explicit action surface.</h2><div className="guide-table"><table><thead><tr><th>Provider</th><th>Supported actions</th><th>Owner pins</th></tr></thead><tbody><tr><td>GitHub</td><td>Read workflow run status; rerun an existing workflow</td><td>Repository</td></tr><tr><td>Cloudflare</td><td>List Worker deployments; promote an existing immutable version to 100%</td><td>Account + Worker</td></tr><tr><td>npm</td><td>Read package latest semver; publish approved tarball with 2FA OTP</td><td>Package + Tarball directory</td></tr></tbody></table></div><p>There is no general HTTP proxy, shell execution, code upload or credential-read tool. Each request expires after two minutes and needs fresh approval. The owner vault auto-locks after five minutes.</p><CodeBlock label="Agent CLI example">{'node packages/cli/dist/index.js action connections\nnode packages/cli/dist/index.js action request --connection work --action github.run-status --run-id 123456\nnode packages/cli/dist/index.js action status REQUEST_ID'}</CodeBlock><p>MCP exposes <code>safegen_list_connections</code>, <code>safegen_request_action</code> and <code>safegen_action_status</code>. <a href="/setup">Choose your client for copyable configuration.</a></p><p>Locking or revoking a connection stops new actions and aborts local in-flight requests. It cannot undo an action the provider has already received or revoke the provider token remotely.</p></article>
      <article id="generator"><span className="guide-eyebrow">04 / Browser-local utility</span><h2>Generate. Copy. Decide what stays.</h2><p><a href="/generator">The generator</a> uses Web Crypto for random passwords, EFF passphrases, PINs and custom patterns. No account is required. The app shell is available offline after a successful first load.</p><p>Copied history stays in memory by default. Keeping history on your device is an explicit opt-in and is <strong>unencrypted</strong>. Exported JSON also contains plaintext credentials. The browser generator is separate from the encrypted owner vault.</p><p>Strength figures estimate the generation method. Arbitrary-password analysis is a heuristic and cannot guarantee a cracking time. Never reuse a password.</p><a href={`${repo}packages/core/README.md`}>Use the generator core in TypeScript ↗</a></article>
      <article id="maintenance"><span className="guide-eyebrow">05 / Keep it maintainable</span><h2>Back up encrypted data. Update deliberately.</h2><p>Stop the broker before vault maintenance. The vault uses AES-256-GCM with Envelope v2 scrypt (N=131072, r=8, p=1) with PBKDF2 compatibility. Keep backups private; restoring requires the backup’s original password. Rotating the live vault password does not change old backups.</p><CodeBlock label="Vault maintenance">{'node packages/cli/dist/index.js vault backup --path PRIVATE_BACKUP_PATH\nnode packages/cli/dist/index.js vault rotate-password\nnode packages/cli/dist/index.js vault restore --path PRIVATE_BACKUP_PATH\nnode packages/cli/dist/index.js vault kdf\nnode packages/cli/dist/index.js broker audit --json'}</CodeBlock><p>There is no master-password recovery. Revoke or rotate provider tokens at the provider when needed. Updating owner code or dependencies must remain a trusted human operation.</p><p>For contributors: <a href={`${repo}docs/architecture.md`}>architecture and boundaries</a> · <a href={`${repo}docs/maintenance.md`}>build, test and Cloudflare deployment</a> · <a href={`${repo}packages/cli/README.md`}>CLI reference</a>.</p></article>
      <article id="troubleshooting"><span className="guide-eyebrow">06 / When something stops</span><h2>Resolve the boundary. Keep the boundary.</h2><details><summary>The client cannot connect</summary><p>Check Node is available to the client, the CLI path is absolute and built, and the server is enabled. The owner must start the separate broker. The agent endpoint is <code>http://127.0.0.1:4767</code>; do not use the private control URL.</p></details><details><summary>The broker rejects startup</summary><p>Check the exact agent OS username and private owner permissions against the isolation guide. Do not run both sides as the same user or elevate the agent to bypass the check.</p></details><details><summary>An action is locked, expired or denied</summary><p>The owner can unlock the vault privately. Expired requests need a new request and fresh approval. A denial is final for that request; do not retry without the owner asking.</p></details><details><summary>The provider rejects an approved action</summary><p>The owner checks token expiry, minimum provider permissions and the pinned resource in their private session. Agent errors intentionally exclude raw provider responses. Never paste the token into a support issue.</p></details><details><summary>Offline loading or copying fails</summary><p>Open the site once online and let its assets finish loading. Copy requires browser permission; use manual selection if it is denied. Clearing site data removes the offline shell and any saved browser history.</p></details></article>
    </div></div>
  </section>;
}
